openapi: 3.1.0
info:
  title: "UserService API"
  description: |
    API для управления пользователями и их автомобилями в приложении для автомойки.

servers:
  - url: http://localhost:8080
    description: Local development server

servers:
  - url: http://localhost:8080/
    description: Production Server

paths:
  /internal/users/superusers:
    get:
      tags: [Internal]
      summary: "Получение списка всех суперпользователей (межсервисное взаимодействие)"
      description: "Endpoint для получения списка Telegram user ID всех пользователей с ролью superuser."
      responses:
        '200':
          description: "Успешный ответ со списком ID суперпользователей."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuperUsersResponse'
        '500':
          description: "Внутренняя ошибка сервера."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  schemas:
    # --- МОДЕЛИ ДАННЫХ ---
    SuperUsersResponse:
      type: object
      properties:
        super_user_ids:
          type: array
          items:
            type: integer
            format: int64
          description: "Список Telegram user ID всех суперпользователей."
          example: [123456789, 987654321]
          
    Error:
      type: object
      properties:
        code:
          type: integer
          description: "Код ошибки."
          example: 400
        message:
          type: string
          description: "Описание ошибки."
          example: "Validation failed."